package recipes_test

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/ushineko/terrariabonker/internal/game"
	"github.com/ushineko/terrariabonker/internal/layout"
	"github.com/ushineko/terrariabonker/internal/memtest"
	"github.com/ushineko/terrariabonker/internal/proc"
	"github.com/ushineko/terrariabonker/internal/recipes"
)

/*
Reading the crafting book out of a game that is not there.

The book is bundled and regenerated by hand, so this runs perhaps once a
release -- which is exactly why it is worth comparing: a walk that quietly
stopped reading a field would produce a book that looks complete and is missing
something, and nobody would look at it again for months.
*/

const (
	base = 0x10000000
	size = 0x80000

	// get_LocalPlayer and the static the base is derived from. Main.player sits
	// at its own offset inside Main's block, because that is how the base is
	// worked out: the resolver finds this address and subtracts the offset.
	code           = base + 0x1000
	staticAt       = base + 0x10000
	playerStatic   = staticAt + layout.MainPlayerOff
	myPlayerStatic = playerStatic + 4
	playerArray    = base + 0x200

	// The recipe array, the recipe objects, and the item objects they point at.
	recipeArr     = base + 0x20000
	recipeObjects = base + 0x21000
	recipeStride  = 0x40
	itemObjects   = base + 0x14000
	itemArrays    = base + 0x15000
	itemStride    = 0x100
	// The ingredient objects, spread far enough apart that a recipe with more
	// of them than the game reads still fits.
	ingObjects   = base + 0x40000
	ingPerRecipe = 64

	/*
		The station-name lookup: the two instructions that load the statics, the
		statics themselves, and what they point at.

		The names come from the game's own tile display names, which are reached
		through two arrays nothing else in the project touches -- so each static
		is found by matching the code that reads it, and that code has to be here
		for any of it to be exercised.
	*/
	tileCodeAt    = base + 0x2000
	legendCodeAt  = base + 0x2100
	lookupStatic  = base + 0x2200
	legendStatic  = base + 0x2204
	lookupArr     = base + 0x30000
	legendArr     = base + 0x31000
	legendText    = base + 0x32000
	stationNameAt = base + 0x32100

	// Which map-legend entry the workbench tile points at, and what it says.
	benchTile   = 18
	benchLegend = 5
	benchName   = "Work Bench"
)

// recipe is one entry the fixture plants.
type recipeImage struct {
	out   int32
	stack int32
	// ing is [item, count] pairs.
	ing [][2]int32
	// tile is the station, or -1 for something made by hand.
	tile int32
	// planted says to write an output item even when its type is zero, which is
	// how the game's own unused slots read.
	planted bool
	// createTile is what the output places, or -1 if it places nothing.
	createTile int32
	placeStyle int32
}

/*
book is the fixture's recipes.

One made by hand and two at a station, so both branches are walked; an output
that places a tile, because that is the table nothing else would notice being
dropped; and an empty slot in the middle, which the game's own array is full of.
*/
var book = []recipeImage{
	{out: 8, stack: 3, ing: [][2]int32{{23, 1}, {9, 1}}, tile: -1, createTile: -1},
	{out: 24, stack: 1, ing: [][2]int32{{9, 7}}, tile: benchTile, createTile: -1},
	{}, // an unused slot: no object behind it at all
	// A slot with an output item whose type is zero, which is what most of the
	// game's own array looks like.
	{out: 0, stack: 1, tile: -1, createTile: -1, planted: true},
	{out: 35, stack: 1, ing: [][2]int32{{22, 5}}, tile: benchTile, createTile: 16, placeStyle: 2},
	// A recipe with no stack written, and more ingredients than the game reads.
	{out: 71, stack: 0, ing: manyIngredients(45), tile: -1, createTile: -1},
}

// manyIngredients is a recipe that takes more than the walk will look at.
func manyIngredients(n int) [][2]int32 {
	out := make([][2]int32, n)
	for i := range out {
		out[i] = [2]int32{int32(100 + i), int32(i + 1)} //nolint:gosec // a small index
	}
	return out
}

// execMem is a fake whose whole buffer is also code, so the two statics the
// station names need can be found in it.
type execMem struct{ *memtest.FakeMem }

func (m *execMem) AllRegions() []proc.Region { return m.Regions() }

func plant(t *testing.T) *execMem {
	t.Helper()
	mem := memtest.New(base, size)
	mem.Exec = []proc.Region{{Start: base, End: base + size, Executable: true}}

	// get_LocalPlayer: mov eax,[Main.player]; mov ecx,[Main.myPlayer]; tail.
	asm := append([]byte{0x8B, 0x05}, u32(playerStatic)...)
	asm = append(asm, 0x8B, 0x0D)
	asm = append(asm, u32(myPlayerStatic)...)
	asm = append(asm, localPlayerTail...)
	mem.PokeBytes(code, asm)
	mem.PokeBytes(playerStatic, u32(playerArray))
	mem.PokeI32(myPlayerStatic, 0)

	mem.PokeBytes(staticAt+layout.MainRecipeOff, u32(recipeArr))
	mem.PokeI32(recipeArr+layout.ArrLenOff, int32(len(book)))
	for i, rec := range book {
		obj := uint32(recipeObjects + i*recipeStride) //nolint:gosec // a planted address
		mem.PokeBytes(recipeArr+layout.ArrDataOff+uint32(i)*4, u32(obj))
		if rec.out == 0 && !rec.planted {
			continue // an unused slot with nothing behind it at all
		}
		made := uint32(itemObjects + i*itemStride) //nolint:gosec // a planted address
		mem.PokeBytes(obj+layout.RecipeCreateItem, u32(made))
		mem.PokeI32(made+layout.ItemType, rec.out)
		mem.PokeI32(made+layout.ItemStack, rec.stack)
		mem.PokeI32(made+layout.ItemCreateTile, rec.createTile)
		mem.PokeI32(made+layout.ItemPlaceStyle, rec.placeStyle)
		mem.PokeI32(obj+layout.RecipeRequiredTile, rec.tile)

		items := uint32(itemArrays + i*itemStride) //nolint:gosec // a planted address
		mem.PokeBytes(obj+layout.RecipeRequiredItem, u32(items))
		mem.PokeI32(items+layout.ArrLenOff, int32(len(rec.ing))) //nolint:gosec // a small count
		for j, pair := range rec.ing {
			ing := ingredientAt(i, j)
			mem.PokeBytes(items+layout.ArrDataOff+uint32(j)*4, u32(ing)) //nolint:gosec // an index
			mem.PokeI32(ing+layout.ItemType, pair[0])
			mem.PokeI32(ing+layout.ItemStack, pair[1])
		}
	}
	plantStationNames(mem)
	return &execMem{mem}
}

// ingredientAt is where one recipe's nth ingredient object goes.
func ingredientAt(recipe, n int) uint32 {
	return uint32(ingObjects + (recipe*ingPerRecipe+n)*itemStride) //nolint:gosec // a planted address
}

/*
plantStationNames writes the two instructions the statics are found through, and
everything behind them.

The lookup is a ushort per tile into the legend, and the legend holds localised
strings -- so a station name is three hops from a tile id, and every hop is a
place the walk could quietly give up and report a book with no station names in
it.
*/
func plantStationNames(mem *memtest.FakeMem) {
	tileCode := append([]byte{0x8B, 0x05}, u32(lookupStatic)...)
	tileCode = append(tileCode, 0x39, 0x70, 0x0C, 0x0F, 0x86, 0, 0, 0, 0,
		0x8D, 0x44, 0x70, 0x10, 0x0F, 0xB7, 0x00, 0x03, 0xC7)
	mem.PokeBytes(tileCodeAt, tileCode)

	legendCode := append([]byte{0x8B, 0x05}, u32(legendStatic)...)
	legendCode = append(legendCode, 0x85, 0xC0, 0x74, 0x24, 0x8B, 0x05, 0, 0, 0, 0,
		0x8B, 0x4D, 0x08, 0x39, 0x48, 0x0C, 0x0F, 0x86, 0, 0, 0, 0,
		0x8D, 0x44, 0x88, 0x10, 0x8B, 0x00)
	mem.PokeBytes(legendCodeAt, legendCode)

	mem.PokeBytes(lookupStatic, u32(lookupArr))
	mem.PokeBytes(legendStatic, u32(legendArr))

	mem.PokeI32(lookupArr+layout.ArrLenOff, 700)
	mem.PokeBytes(lookupArr+layout.ArrDataOff+benchTile*2, []byte{benchLegend, 0})

	mem.PokeI32(legendArr+layout.ArrLenOff, 64)
	mem.PokeBytes(legendArr+layout.ArrDataOff+benchLegend*4, u32(legendText))
	mem.PokeBytes(legendText+uint32(layout.LocalizedTextValue), u32(stationNameAt))
	mem.PlantMonoString(stationNameAt, benchName)
}

func u32(v uint32) []byte {
	return []byte{byte(v), byte(v >> 8), byte(v >> 16), byte(v >> 24)}
}

// localPlayerTail is the pattern the resolver looks for, pinned against the
// Python by the locate package's own tests.
var localPlayerTail = []byte{
	0x39, 0x48, 0x0C, 0x0F, 0x86, 0x07, 0x00, 0x00, 0x00,
	0x8D, 0x44, 0x88, 0x10, 0x8B, 0x00, 0xC3,
}

// pyPlant is the same image as Python source.
func pyPlant() string {
	var b strings.Builder
	fmt.Fprintf(&b, `
import json, os, struct, sys
sys.path.insert(0, os.getcwd())
sys.path.insert(0, os.path.join(os.getcwd(), "tests"))
from conftest import FakeMem
from terrariabonker import inventory as I, layout as L, locate, recipes as R
mem = FakeMem(%d, %d)
code = (b"\x8b\x05" + struct.pack("<I", %d) + b"\x8b\x0d" + struct.pack("<I", %d)
        + locate._LOCALPLAYER_TAIL)
mem.poke_bytes(%d, code)
mem.poke_bytes(%d, struct.pack("<I", %d))
mem.poke_i32(%d, 0)
locate._exec_regions = lambda m: [(%d, %d)]
R._exec_regions = lambda m: [(%d, %d)]
mem.poke_bytes(%d + L.MAIN_RECIPE_OFF, struct.pack("<I", %d))
mem.poke_i32(%d + I.ARR_LEN_OFF, %d)
mem.poke_bytes(%d, b"\x8b\x05" + struct.pack("<I", %d)
               + bytes([0x39, 0x70, 0x0C, 0x0F, 0x86, 0, 0, 0, 0,
                        0x8D, 0x44, 0x70, 0x10, 0x0F, 0xB7, 0x00, 0x03, 0xC7]))
mem.poke_bytes(%d, b"\x8b\x05" + struct.pack("<I", %d)
               + bytes([0x85, 0xC0, 0x74, 0x24, 0x8B, 0x05, 0, 0, 0, 0,
                        0x8B, 0x4D, 0x08, 0x39, 0x48, 0x0C, 0x0F, 0x86, 0, 0, 0, 0,
                        0x8D, 0x44, 0x88, 0x10, 0x8B, 0x00]))
mem.poke_bytes(%d, struct.pack("<I", %d))
mem.poke_bytes(%d, struct.pack("<I", %d))
mem.poke_i32(%d + I.ARR_LEN_OFF, 700)
mem.poke_bytes(%d + I.ARR_DATA_OFF + %d * 2, struct.pack("<H", %d))
mem.poke_i32(%d + I.ARR_LEN_OFF, 64)
mem.poke_bytes(%d + I.ARR_DATA_OFF + %d * 4, struct.pack("<I", %d))
mem.poke_bytes(%d + R.LOCALIZEDTEXT_VALUE, struct.pack("<I", %d))
mem.plant_mono_string(%d, %q)
`, base, size, playerStatic, myPlayerStatic, code,
		playerStatic, playerArray, myPlayerStatic,
		base, base+size, base, base+size,
		staticAt, recipeArr, recipeArr, len(book),
		tileCodeAt, lookupStatic, legendCodeAt, legendStatic,
		lookupStatic, lookupArr, legendStatic, legendArr,
		lookupArr, lookupArr, benchTile, benchLegend,
		legendArr, legendArr, benchLegend, legendText,
		legendText, stationNameAt, stationNameAt, benchName)

	for i, rec := range book {
		obj := recipeObjects + i*recipeStride
		fmt.Fprintf(&b, "mem.poke_bytes(%d + I.ARR_DATA_OFF + %d * 4, struct.pack(\"<I\", %d))\n",
			recipeArr, i, obj)
		if rec.out == 0 && !rec.planted {
			continue
		}
		made := itemObjects + i*itemStride
		items := itemArrays + i*itemStride
		fmt.Fprintf(&b, `
mem.poke_bytes(%d + R.RECIPE_CREATE_ITEM, struct.pack("<I", %d))
mem.poke_i32(%d + R.ITEM_TYPE, %d)
mem.poke_i32(%d + R.ITEM_STACK, %d)
mem.poke_i32(%d + R.ITEM_CREATE_TILE, %d)
mem.poke_i32(%d + R.ITEM_PLACE_STYLE, %d)
mem.poke_i32(%d + R.RECIPE_REQUIRED_TILE, %d)
mem.poke_bytes(%d + R.RECIPE_REQUIRED_ITEM, struct.pack("<I", %d))
mem.poke_i32(%d + I.ARR_LEN_OFF, %d)
`, obj, made, made, rec.out, made, rec.stack, made, rec.createTile,
			made, rec.placeStyle, obj, rec.tile, obj, items, items, len(rec.ing))
		for j, pair := range rec.ing {
			ing := ingredientAt(i, j)
			fmt.Fprintf(&b, `
mem.poke_bytes(%d + I.ARR_DATA_OFF + %d * 4, struct.pack("<I", %d))
mem.poke_i32(%d + R.ITEM_TYPE, %d)
mem.poke_i32(%d + R.ITEM_STACK, %d)
`, items, j, ing, ing, pair[0], ing, pair[1])
		}
	}
	return b.String()
}

var repoRoot = func() string {
	_, file, _, _ := runtime.Caller(0)
	return filepath.Dir(filepath.Dir(filepath.Dir(file)))
}()

func askPython(t *testing.T, script string, into any) {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, "python3", "-c", script) //nolint:gosec // a generated fixture
	cmd.Dir = repoRoot
	out, err := cmd.CombinedOutput()
	if err != nil && strings.Contains(string(out), "ModuleNotFoundError") {
		t.Skip("the Python package is not importable here")
	}
	require.NoErrorf(t, err, "asking the Python: %s", out)
	require.NoError(t, json.Unmarshal(out, into))
}

// Both walk the same array to the same book.
func TestExtractingMatchesThePython(t *testing.T) {
	var want map[string]any
	askPython(t, pyPlant()+`
print(json.dumps(R.extract(mem)))`, &want)

	got, err := recipes.Extract(plant(t))
	require.NoError(t, err)

	blob, err := json.Marshal(struct {
		Recipes   []game.Recipe     `json:"recipes"`
		Stations  map[string]string `json:"stations"`
		TileIcons map[string][]int  `json:"tileicons"`
	}{got.Recipes, got.Stations, got.TileIcons})
	require.NoError(t, err)
	var mine map[string]any
	require.NoError(t, json.Unmarshal(blob, &mine))
	require.Equal(t, want, mine, "the two read different books")
}

/*
And the book itself is what the fixture planted.

The comparison above only says the two agree, and two walks that both stopped
after the output item agree perfectly.
*/
func TestTheBookIsWhatWasPlanted(t *testing.T) {
	got, err := recipes.Extract(plant(t))
	require.NoError(t, err)
	require.Len(t, got.Recipes, 4, "the unused slots were read as recipes")

	torch := got.Recipes[0]
	require.Equal(t, 8, torch.Out, "a different item is made")
	require.Equal(t, 3, torch.N, "a different number of them")
	require.Equal(t, [][]int{{23, 1}, {9, 1}}, torch.Ing, "different ingredients")
	require.Nil(t, torch.Tile, "something made by hand was given a station")

	sword := got.Recipes[1]
	require.NotNil(t, sword.Tile, "a recipe made at a station has none")
	require.Equal(t, 18, *sword.Tile, "a different station")

	require.Equal(t, map[string][]int{"35": {16, 2}}, got.TileIcons,
		"the tile a placeable output draws from was not recorded")

	// A recipe with no stack written makes one, not none.
	last := got.Recipes[3]
	require.Equal(t, 71, last.Out)
	require.Equal(t, 1, last.N, "a recipe with no stack was read as making nothing")
	require.Len(t, last.Ing, 40, "more ingredients were read than the game holds")

	require.Equal(t, map[string]string{"18": benchName}, got.Stations,
		"the station name was not read out of the game's own table")
}

// A game with no recipe array says so rather than returning an empty book.
func TestExtractingWithNoArray(t *testing.T) {
	mem := plant(t)
	mem.PokeBytes(staticAt+layout.MainRecipeOff, u32(0))

	_, err := recipes.Extract(mem)
	require.ErrorIs(t, err, recipes.ErrNoRecipes)
}

// An array whose length is absurd is a wrong pointer, not a book.
func TestExtractingAnImplausibleArray(t *testing.T) {
	mem := plant(t)
	mem.PokeI32(recipeArr+layout.ArrLenOff, recipes.MaxRecipes+1)

	_, err := recipes.Extract(mem)
	require.ErrorIs(t, err, recipes.ErrNoRecipes)
}

/*
Saving writes the shape the game package reads back.

The two halves are in different packages and only the file connects them, so a
field renamed on one side is a book that loads empty.
*/
func TestSavingIsReadBack(t *testing.T) {
	got, err := recipes.Extract(plant(t))
	require.NoError(t, err)

	path := filepath.Join(t.TempDir(), "recipes.json")
	require.NoError(t, recipes.Save(got, path))

	raw, err := os.ReadFile(path) //nolint:gosec // a path this test made
	require.NoError(t, err)
	var back game.Recipes
	require.NoError(t, json.Unmarshal(raw, &back))
	require.Equal(t, got.Recipes, back.Recipes, "the recipes did not survive the file")
	require.Equal(t, got.TileIcons, back.TileIcons, "the tile icons did not")
	require.NotContains(t, string(raw), ", ", "the file was written with spaces in it")
}

/*
A pattern that matches twice names nothing.

Two candidates mean the shape is no longer unique to the instruction that was
meant, and picking one would name the wrong static -- which does not fail, it
produces station names read out of unrelated memory.
*/
func TestASecondMatchGivesUpOnTheNames(t *testing.T) {
	mem := plant(t)
	got, err := recipes.Extract(mem)
	require.NoError(t, err)
	require.NotEmpty(t, got.Stations, "the fixture never named a station to begin with")

	twice := plant(t)
	tileCode := twice.Read(tileCodeAt, 24)
	twice.PokeBytes(tileCodeAt+0x1000, tileCode)

	got, err = recipes.Extract(twice)
	require.NoError(t, err)
	require.Empty(t, got.Stations, "an ambiguous pattern was resolved anyway")
	require.NotEmpty(t, got.Recipes, "the book itself was lost with the names")
}

/*
A station the lookup cannot name is left unnamed, rather than named from
whatever is at that address.

Three ways it can fail, and all three are a read that succeeds and means
nothing: a tile past the end of the lookup, a legend index past the end of the
legend, and a name that is there but empty. None of them fails visibly -- the
book comes out with a station called something out of unrelated memory.
*/
func TestStationsThatCannotBeNamed(t *testing.T) {
	const (
		pastLookup = 6000 // beyond the lookup array's length
		pastLegend = 200  // beyond the legend array's length
		emptyName  = 21   // a tile whose name is there and blank
		badText    = base + 0x33000
		emptyText  = base + 0x33100
		emptyStr   = base + 0x33200
	)

	mem := plant(t)
	// Something plausible at every address the missing guard would read.
	mem.PokeBytes(lookupArr+layout.ArrDataOff+pastLookup*2, []byte{1, 0})
	mem.PokeBytes(legendArr+layout.ArrDataOff+1*4, u32(badText))
	mem.PokeBytes(badText+uint32(layout.LocalizedTextValue), u32(stationNameAt))

	mem.PokeBytes(lookupArr+layout.ArrDataOff+emptyName*2, []byte{pastLegend, 0})
	mem.PokeBytes(legendArr+layout.ArrDataOff+pastLegend*4, u32(badText))

	mem.PokeBytes(lookupArr+layout.ArrDataOff+19*2, []byte{6, 0})
	mem.PokeBytes(legendArr+layout.ArrDataOff+6*4, u32(emptyText))
	mem.PokeBytes(emptyText+uint32(layout.LocalizedTextValue), u32(emptyStr))
	mem.PlantMonoString(emptyStr, "")

	// Three more recipes, one per way of failing.
	for i, tile := range []int32{pastLookup, emptyName, 19} {
		slot := len(book) + i
		obj := uint32(recipeObjects + slot*recipeStride)                    //nolint:gosec // a planted address
		made := uint32(itemObjects + slot*itemStride)                       //nolint:gosec // a planted address
		mem.PokeI32(recipeArr+layout.ArrLenOff, int32(slot+1))              //nolint:gosec // a small count
		mem.PokeBytes(recipeArr+layout.ArrDataOff+uint32(slot)*4, u32(obj)) //nolint:gosec // an index
		mem.PokeBytes(obj+layout.RecipeCreateItem, u32(made))
		mem.PokeI32(made+layout.ItemType, int32(500+i)) //nolint:gosec // a small index
		mem.PokeI32(made+layout.ItemStack, 1)
		mem.PokeI32(made+layout.ItemCreateTile, -1)
		mem.PokeI32(obj+layout.RecipeRequiredTile, tile)
	}

	got, err := recipes.Extract(mem)
	require.NoError(t, err)
	require.Equal(t, map[string]string{"18": benchName}, got.Stations,
		"a station was named from memory the lookup does not reach")
}
